config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses
  root to: "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  title       :string
#  autor       :integer
#  day         :integer
#  hour_range  :text
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Course < ApplicationRecord
  belongs_to :user
  serialize :hour_range

  validates :title, :description, presence: true
	validates :description,	length: { minimum: 20 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :courses

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :create_ransack_object

  def create_ransack_object
    @q = Course.ransack(params[:q])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_course, only: [:edit,:show,:update,:destroy]
  before_action :authenticate_user!,only: [:create,:destroy,:update]

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.user = current_user
    if @course.save
      flash[:notice] = 'The course have been saved'
      redirect_to course_path(id: @course.id, it_was: 'created')
    else
      render :new
    end
  end

  def edit
    if current_user != @course.user
      flash[:alert] = "I'm sorry, you are not the autor of this course"
      redirect_to root_path
    end
  end

  def index
    @courses = @q.result(distinct: true)
  end

  private

  def course_params
    params.require(:course).permit(:title,:description)
  end

  def find_course
    @course = Course.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2><%= action %> Curso</h2>
          </div>
          <div class="panel-body">
            <%= form_for(@course) do |course| %>

              <% if @course.errors.any? %>
                <div class="error_explanation">
                  <h2><%= pluralize(@course.errors.count, "error")%> won´t let this course to being saved:</h2>

                  <ul>
                    <% @course.errors.full_messages.each do |message| %>
                      <li class="danger"><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="row">
                <div class="col-md-12">
                  <div class= "form-group">
                    <%= course.label :title %>
                    <%= course.text_field :title, class: 'form-control' %>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <%= course.label :description %>
                    <%= course.text_area :description,size: "30x10", class: 'form-control markdown-editable' %>
                  </div>
                </div>
              </div>
              <div class="actions">
                <%= link_to raw('<span class="glyphicon glyphicon-remove"></span> Cancel'), courses_path, class: 'btn btn-primary btn-large' %>
                <%= button_tag(type: "submit", class: "btn btn-success btn-large", name: "Save Course", value: "Save Course") do %>
                  <span class="glyphicon glyphicon-ok"></span> Save Course
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form', course: @course,action: 'Edit' %>

app/views/courses/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 ">
        <h1 class="text-center">CURSOS</h1>
        <% @courses.each do |course| %>
          <h2><%= course.title %></h2>
          <p class="text-justify"><%= truncate(course.description, :length => 250) %></p>
          <p><%= link_to 'View',course %></p>
          <p>
            <%= link_to 'Edit',edit_course_path(course) %>
            <%= link_to 'Remove',course, method: :delete,data: {confirm: 'Are you sure to delete this course'} %>
          </p>
        <% end %>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<%= render 'form', course: @course, action: 'New' %>

app/views/courses/show.html.erb
<%= render 'form', course: @course, action: 'New' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CICLO DE FORMACIÓN FREIRE", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
       <ul class="nav navbar-nav">
         <li><%= link_to 'Cursos', courses_path %></li>
       </ul>
     <% end %>

      <%= search_form_for(@q, url: root_path, html: {class: 'navbar-form navbar-left'}) do |f| %>
        <div class="form-group">
          <%= f.search_field :title_or_description_cont, class: 'form-control', placeholder: 'Buscar pregunta' %>
        </div>
        <%= f.submit "Buscar", class: 'btn btn-default' %>
      <% end %>


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-plus"></span> <%= current_user.email.split("@")[0] %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to raw("<span class='glyphicon glyphicon-remove'></span> Cerrar Sesión"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to raw("<span class='glyphicon glyphicon-user'></span> Inicia sesión"), new_user_session_path %> </li>
          <li><%= link_to raw("<span class='glyphicon glyphicon-plus'></span> Registrate"), new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ciclo de formación CEP Paulo Freire</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script>
      $('.alert').fadeIn(500).css("opacity","0.85").delay(2500).slideUp(900);
      $('.alerts').on('click','.alert',function(){$(this).remove()});
    </script>
  </body>
</html>